version: "3.7"
services:
  server:
    build: .
    ports:
      - 9093:9093
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

